### ISSUE TITLE
Issues Updating 1.4.0 to 2.3.0

### ISSUE THREAD

**Issue by jamsoft** [dotnet/systemweb-adapters#669]
### Describe the bug
I have updated the nuget packages to the latest version. All was working with 1.4.0. I have migrated the configuration as per the [documentation](https://learn.microsoft.com/en-us/aspnet/core/migration/fx-to-core/inc/remote-app-setup?view=aspnetcore-10.0&source=recommendations&pivots=manual).

Now when I compile, I get a very confusing compiler error:

```
Mvc.g.cs(59,62): Error CS1061 : 'HttpContextBase' does not contain a definition for 'GetRequestServices' and no accessible extension method 'GetRequestServices' accepting a first argument of type 'HttpContextBase' could be found (are you missing a using directive or an assembly reference?)
```

### To Reproduce
I think it's too specific to my case to even attempt this.

### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*:
- MVC5
- .NET Framework Version: 4.8.1
- IIS Version: Express
- Windows Version: 11

*ASP.NET Core Application*:
- Targeted .NET version: 10.0
- .NET SDK version: 10.0

**Comment by twsouthwick** [comment]
Did you update all the related packages to 2.3.0? The error appears to indicate that the source generators are running to create the ability to hook up dependency injection (which is a 2.2.0 feature), but the type is not available (which is in a separate package but same version).

If you haven't already, clean your artifacts/bin/obj directories and restore again. Otherwise, I'll need a repro

**Comment by jamsoft** [comment]
Indeed, all packages were updated. I've been looking into this again today and it seems when the updates were done it still left a lot of cruft for v 1.4.0 behind in the project files.

Cleaning all of that up, clearing down bin/obj etc I'm still left with the same compiler issues. Going to have to park this again now.
